### PR TITLE
Add edit option to docs

### PR DESCRIPTION
**Pull request by bdpedigo**

### CODE REVIEW

**Comment by ceesem** [comment]
Could you describe what this would do?

**Comment by bdpedigo** [comment]
adds these buttons to the top right to view/edit page source. helpful for making quick edits to documentation IMO

isn't perfect because it wont bring you to the underlying docstring w/o some additional configuration but i think its better than nothing

Screenshot 2024-05-15 at 12 54 33 PM

**Comment by ceesem** [comment]
I confess, I always hate when I see those buttons because they aren't designed for the reader. I can see it being useful during development but I don't want them in the outward-facing interface.

**Comment by bdpedigo** [comment]
ok I'll close - but I feel they encourage people to give feedback and improve the documentation, and I find them minimally invasive, personally

**Pull request closed without merging**
